version: "3"

services:
  dnsmasq:
    container_name: dnsmasq
    image: ghcr.io/lostmaniac/dnsmasq:latest
    restart: always
    ports:
      - "53:53/udp"
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
      - ./log/dnsmasq:/var/log/dnsmasq
      - ./logrotate/dnsmasq:/etc/logrotate.d/dnsmasq
