version: "3"

services:
  dnsmasq:
    container_name: dnsmasq
    image: ghcr.io/lostmaniac/dnsmasq:latest
    restart: always
    ports:
      - "53:53"
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
      - ./log:/var/log/dnsmasq
